### ISSUE TITLE
Enable choice of statically vs dynamical linking

### ISSUE THREAD

**Issue by maybeec** [devonfw-forge/solicitor#35]
As a user I would like to point solicitor at the beginning of the analysis of my java maven project to the fact, that my software will be distributed as a fat runnable jar in order to enable solicitor make its decisions correctly as of a different usage pattern applied. It currently automatically implies usage pattern to always be DYNAMICAL_LINKING in case of a maven dependency, which is not correct as it depends on the packaging and distribution.

**Comment by ohecker** [comment]
Change: Extend the Enum `UsagePattern` to contain 3 different values:
* `DYNAMIC_LINKING`
* `STATIC_LINKING`
* `STANDALONE_PRODUCT`

These values can then be used as possible values in the configuration of the reader:

```
    "readers" : [ {
      "type" : "maven",
      "source" : "file:${cfgdir}/input/some_licenses.xml",
      "usagePattern" : "STATIC_LINKING"
    } ]
```
Note that even if Solicitor now supports the different usage scenarios the business rules need to be adopted to actually make use of this information.
